on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Build
        id: build
        uses: NisargShah1410/js-custom-action@v1.2
        with:
          language-name: 'python'
      
      - name: run the build command
        run: ${{ steps.build.outputs.com}}
        
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.build.outputs.time }}"
